#!/bin/bash
#
# Packages the necessary files into a .zip archive

cd src

files=(
  "./manifest.json"
  "./icons/*"
  "./background.js"
  "./content.js"
  "./style.css"
)

archive_name="github-markdown-printer.zip"

zip -9 "$archive_name" ${files[*]}
mv "$archive_name" ~/Desktop
